export default {
  nodeName: '发起人',
  type: 0,
  nodeId: 1,
  conditionList: [],
  nodeUserList: [],
  childNode: {
    nodeName: '审核人',
    type: 1,
    nodeId: 2,
    childNode: {
      nodeName: '路由',
      type: 4,
      nodeId: 3,
      conditionList: [],
      nodeUserList: [],
      childNode: {
        nodeName: '抄送人',
        type: 2,
        nodeId: 4,
        childNode: null,
        nodeUserList: [],
      },
      conditionNodes: [{
        nodeName: '条件1',
        type: 3,
        nodeId: 6,
        conditionList: [{
          type: 1,
        }],
        nodeUserList: [{
          targetId: 85,
          type: 1,
          name: '娃娃乐',
        }],
        childNode: {
          nodeName: '审核人',
          type: 1,
          nodeId: 5,
          conditionList: [],
          nodeUserList: [],
          childNode: null,
          conditionNodes: [],
        },
        conditionNodes: [],
      }, {
        nodeName: '条件2',
        type: 3,
        nodeId: 7,
        conditionList: [],
        nodeUserList: [],
        childNode: {
          nodeName: '路由',
          type: 4,
          nodeId: 30,
          conditionList: [],
          nodeUserList: [],
          conditionNodes: [{
            nodeName: '条件3',
            type: 3,
            nodeId: 60,
            conditionList: [{
              type: 1,
            }],
            nodeUserList: [{
              targetId: 85,
              type: 1,
              name: '娃娃乐',
            }],
            childNode: {
              nodeName: '审核人',
              type: 1,
              nodeId: 50,
              conditionList: [],
              nodeUserList: [],
              childNode: null,
              conditionNodes: [],
            },
            conditionNodes: [],
          }, {
            nodeName: '条件2',
            type: 3,
            nodeId: 70,
            conditionList: [],
            nodeUserList: [],
            childNode: null,
            conditionNodes: [],
          }],
          childNode: {
            nodeName: '抄送人',
            type: 2,
            nodeId: 40,
            childNode: null,
            nodeUserList: [],
          },
        },
      }],
    },
    nodeUserList: [],
  },
  conditionNodes: [],
};
